### ISSUE TITLE
browser causing freezing at dc/ opening main menu in normal matchmaking

### ISSUE THREAD

**Issue by Lagg1** [GetDotaStats/GetDotaLobby#7]
just what it says, lobby browser (most likely) causes the main menu to load really slowly. game is unresponsive after pressing the UI button to disconnect from endgame scoreboard until it finally goes back to the main menu.. 
Also, similar thing happens if I try to open main menu while connected to a game, only difference is that its not as bad as when disconnecting

Not Critical but really annoying

**Comment by bmddota** [comment]
Thanks for the report.  I too have found this issue and am working on a permanent fix.  For now, you can alleviate the issue by doing a "/disconnect" in the LX Chat window before playing/watching a game, as the delay is caused by all of the received messages getting processed/displayed at once.  I should have a fix for this in the next patch.

**Comment by bmddota** [comment]
Lagg1 the latest release (.37) should fix this issue.  Please let me know if it doesn't or if you see any issues.  You can download the latest release by rerunning the LXUpdater.vbs script or downloading it anew from https://github.com/GetDotaStats/GetDotaLobby/raw/master/LXUpdater.zip

**Comment by Lagg1** [comment]
Yeah, fixed now, good job
